# Generated by Django 6.0.1 on 2026-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stressrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressrecord',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stressrecord',
            name='expense_ratio',
            field=models.FloatField(default=0),
        ),
    ]
